### ISSUE TITLE
[Unsupported NAL Type 6] & [Unsupported NAL Type 9]

### ISSUE THREAD

**Issue by SimonCraenen** [vladmandic/stream-rtsp#13]
I'm trying to follow this approach: Using RTSP to WebRTC.

My camera's main stream is set to use codec H.264.
I'm on windows.
When I run stream.exe I receive alternating [Unsupported NAL Type 6] & [Unsupported NAL Type 9] errors in the terminal.

Any help would be appreciated

**Comment by vladmandic** [comment]
NAL (network abstraction layer) type 6 is a SEI data (supplemental enhancement information) and type 9 is AUD (access unit delimiter)

NAL is meant for decoder to provide additional information on how to use the VCL data that follows (actual video data) and its obsolete in H.264 since a while.

As far as this library goes, it doesn't care about NAL signals as it only re-encapsulates H.264 stream from RTSP, it doesn't decode/re-encode it. So I could try treating it as non-critical error and see if the resulting stream is still usable - but that depends if VCL data after NAL packet is complete instead of partial. But...Its going to take a while and not sure if its going to work or not.

I suggest you try <https://github.com/deepch/RTSPtoWeb>, if it works? If yes, I can port some of its changes here as well.

**Comment by vladmandic** [comment]
closing as no follow-up.
