### ISSUE TITLE
HTTPS is not working (CORS - NAL type 6)

### ISSUE THREAD

**Issue by unbranched** [vladmandic/stream-rtsp#16]
As the configuration for "Using RTSP to WebRTC" says:
`"httpsPort": 8001, // port for local https server`

Visiting https://<host>:8001/client/webrtc.html is not working due to CORS:

Browser console:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://<host>:8002/stream/codec/reowhite. (Reason: CORS request did not succeed). Status code: (null).`

**Comment by vladmandic** [comment]
i've just tried with chrome 110, 111 and 112, no issues.  
what is your browser?
also, cors error may be false here, post the console log as well.

you can also try to enable cors headers, but i don't want to do that by default if i know why.
see <https://github.com/vladmandic/stream-rtsp/blob/f7d6e15bc3b4cd43b11f06b02bd4a9a0014c27c7/server/serve.js#L126>

**Comment by unbranched** [comment]
I'm on Linux. Before it used Firefox, now tried on Chrome and these are the results.

Default installation, browser argues about Mixed Content:
`webrtc.js:58 Mixed Content: The page at 'https://<host>:8001/client/webrtc.html' was loaded over HTTPS, but requested an insecure resource 'http://<host>:8002/stream/codec/reowhite'. This request has been blocked; the content must be served over HTTPS.`

So I replaced all four "http://" of the file client/webrtc.js with "https://" and this is the browser error:
`GET https://<host>:8002/stream/codec/reowhite net::ERR_SSL_PROTOCOL_ERROR`

The only output I see on console when I visit the page is:
```
...
2023-03-01 16:19:18 DATA:  stream: [Unsupported NAL Type 6]
2023-03-01 16:19:18 DATA:  stream: [Unsupported NAL Type 6]
2023-03-01 16:19:18 DATA:  GET/2.0 full 200 text/html; charset=utf-8 885 /client/webrtc.html ::ffff:192.168.1.80
2023-03-01 16:19:18 DATA:  stream: [Unsupported NAL Type 6]
2023-03-01 16:19:18 DATA:  GET/2.0 full 200 text/javascript; charset=utf-8 3315 /client/webrtc.js ::ffff:192.168.1.80
2023-03-01 16:19:18 DATA:  stream: [Unsupported NAL Type 6]
2023-03-01 16:19:18 DATA:  GET/2.0 full 200 application/json; charset=utf-8 462 /config.json ::ffff:192.168.1.80
2023-03-01 16:19:18 DATA:  GET/2.0 full 200 image/x-icon 5063 /favicon.ico ::ffff:192.168.1.80
2023-03-01 16:19:18 DATA:  stream: [Unsupported NAL Type 6]
2023-03-01 16:19:18 DATA:  stream: [Unsupported NAL Type 6]
...
```

**Comment by vladmandic** [comment]
you cannot just replace http with https, that's pointless.
but you can access the original page over `http://<host>:8000/client/webrtc.html`

but `unsupported NAL type 6` is a no-go.
That method is fastest and has least requirements, but that is because there is no actual video re-encoding, it only un-wraps the headers and re-wraps them for consumption in browser. In your case, actual stream seems to be a sub-variant of H.264 format which is not supported by your browser.

check if your camera has an alternative url for serving clean h264 video stream and use that in `config.json` `url` setting.
if not, you may need to go down the reencoding route (see other methods i've listed in README).

**Comment by unbranched** [comment]
you cannot just replace http with https, that's pointless.
    but you can access the original page over http://:8000/client/webrtc.html

It was just to remove the mixed content problem. Yes, the http page on port 8000 works.

    but unsupported NAL type 6 is a no-go.

Is this the cause of ERR_SSL_PROTOCOL_ERROR?

    you may need to go down the reencoding route (see other methods i've listed in README).

Yes I already succesfully use the HLS method, I just wanted to try Webrtc.

**EDIT: answer by [vladmandic](https://github.com/vladmandic)**

    Is this the cause of ERR_SSL_PROTOCOL_ERROR?

not at all, this is actual media stream format coming from the video camera - its in a format that browser cannot understand without reencoding.

**Comment by unbranched** [comment]
> not at all, this is actual media stream format coming from the video camera - its in a format that browser cannot understand without reencoding.

Got it, but why the browser is able to show it in a unencrypted connection anyway?
Thanks, this is mostly informative to me now.

The camera doesn't have an alternative url, so I have no other choice to stay with HLS.

I will also keep the CORS in title as the browser message can mislead other users.

**Comment by vladmandic** [comment]
lets separate 3 unrelated things:

- cannot mix http and https. this is enforced by most modern browsers due to security concerns. and since you cannot just upgrade http to https, you cannot run both via https. but you can downgrade https to http, so both run as http.
- cors issue. again, enforced by brain-dead browser and it should NOT be enforced for localhosts. but if you want to enable CORS headers on server, feel free to do so, i've pointed out the line in the code where to do it.
- unsupported NAL type 6. that means that media stream received from camera cannot be fully understood. perhaps it plays ok, perhaps it doesn't play at all - but something is missing from the stream as it cannot be understood. if its in some extended frame info that nobody cares about, then its ignorable. if its in codec itself, then its a no-go. i cant tell where it is since i'm not decoding the stream, i'm only re-encapsulating it (thats why its so much faster as reencoding would take 20x more cpu).
