### ISSUE TITLE
How to properly close the connection and release memory

### ISSUE THREAD

**Issue by geohuz** [vladmandic/stream-rtsp#7]
I'm not sure when the videoElem is removed from then DOM then everything created by webrtc function is being released? I'm using it in a react application, wondering what should I cleanup upon unmounting the videoElem element ( to avoid memory leaks).

Thanks

**Comment by vladmandic** [comment]
That question is waaay trickier than it sounds.  

First, JavaScript engine will mark DOM element as unused as soon as its no longer referenced.  
and you can force-ensure that by setting it to null value (normally thats not needed, its just if you really want to make sure).  

But...JS by definition relies on dynamic memory management and the fact that any object is marked as unused, doesn't mean that JS engine will actually run garbage collection immediately - and until GC runs, memory is still allocated.   

What makes it even worse is that normal GC skips objects which allocate anything on GPU - which pretty much means any `media` or `canvas` element. GC will still run for those, but far less frequently - and there is no real rule how frequent since it depends on the engine and version. for example, Chrome changed how often GC runs on such objects in Chrome 96 (since then it runs much less frequently than before).

In fact, GC on such objects runs so infrequently that I prefer to reuse them as much as possible so I don't have to create new ones.  

Other than that, not much else I can do about that.  
If you have any questions, feel free to add to the thread, but I'll close the issue for now since this is not strictly a bug.
